"""Shared finance taxonomy and skill vocabulary for collection and the static site.

Career-guide skills are examples, never universal hiring requirements.
"""

import re
from functools import lru_cache

# Specific specialist titles precede generic accounting / finance titles.
# Each entry: family, title phrases, domain skills, collection query.
SPECIALISMS = [
    ("Finance Leadership", ["chief financial officer", "cfo", "finance director", "head of finance", "financial controller", "group controller"],
     ["capital allocation", "board reporting", "financial strategy", "business partnering", "internal controls"], "finance director"),
    ("Finance Systems & Transformation", ["sap fico", "sap fi consultant", "sap functional", "oracle financials", "finance transformation", "finance systems", "financial systems", "sap trm", "sap rar"],
     ["sap fi", "sap s/4hana", "oracle fusion", "process improvement", "finance transformation"], "finance transformation"),
    ("Financial Crime & KYC", ["kyc", "aml", "anti money laundering", "anti-money laundering", "financial crime", "sanctions", "transaction monitoring"],
     ["kyc", "aml", "customer due diligence", "sanctions screening", "transaction monitoring"], "aml kyc"),
    ("Actuarial", ["actuarial", "actuary"],
     ["actuarial modelling", "reserving", "ifrs 17", "solvency ii", "prophet", "axis"], "actuarial"),
    ("Insurance", ["insurance", "reinsurance", "underwriter", "underwriting", "claims analyst", "claims manager", "bancassurance"],
     ["underwriting", "claims management", "reinsurance", "policy administration", "insurance pricing"], "insurance underwriting"),
    ("Quantitative Finance", ["quantitative analyst", "quantitative researcher", "quant researcher", "quant analyst", "quantitative finance", "quantitative trader"],
     ["derivatives pricing", "stochastic calculus", "backtesting", "python", "time series"], "quantitative finance"),
    ("Risk Management", ["credit risk", "market risk", "liquidity risk", "operational risk", "model risk", "risk analyst", "risk manager", "risk modelling"],
     ["credit risk", "value at risk", "stress testing", "basel", "ifrs 9", "model validation"], "risk analyst"),
    ("Investment Banking & Deals", ["investment banking", "investment banker", "mergers and acquisitions", "m&a", "transaction advisory", "transaction services", "corporate development", "private equity", "venture capital", "valuation analyst"],
     ["valuation", "discounted cash flow", "financial modelling", "due diligence", "mergers and acquisitions"], "investment banking"),
    ("Investment Research", ["equity research", "investment research", "credit research", "fixed income research", "investment analyst"],
     ["equity research", "financial statements", "valuation", "fixed income", "financial modelling"], "equity research"),
    ("Asset & Wealth Management", ["wealth", "portfolio manager", "portfolio analyst", "asset management", "investment advisor", "investment adviser", "mutual fund", "financial planner"],
     ["portfolio management", "asset allocation", "investment suitability", "performance attribution", "financial planning"], "wealth management"),
    ("Fund Accounting", ["fund accounting", "fund accountant", "nav analyst", "nav calculation"],
     ["nav calculation", "fund accounting", "corporate actions", "fund administration", "reconciliation"], "fund accounting"),
    ("Investment Operations", ["investment operations", "trade settlement", "trade operations", "securities operations", "corporate actions", "custody", "middle office", "trade support", "securities trader", "equity trader", "sales and trading"],
     ["trade settlement", "corporate actions", "reconciliation", "derivatives", "collateral management"], "investment operations"),
    ("Trade Finance", ["trade finance", "documentary credit", "export finance"],
     ["letter of credit", "bank guarantee", "ucp 600", "documentary collections", "trade finance"], "trade finance"),
    ("Banking & Lending", ["banking", "banker", "loan officer", "loan operations", "loan processing", "credit appraisal", "credit underwriter", "mortgage", "bank operations", "branch manager", "credit analyst", "credit manager"],
     ["credit appraisal", "loan underwriting", "loan documentation", "banking operations", "financial statements"], "banking credit analyst"),
    ("Cost & Management Accounting", ["cost accountant", "cost accounting", "management accountant", "costing", "plant controller"],
     ["standard costing", "inventory valuation", "variance analysis", "cost accounting", "margin analysis"], "cost accountant"),
    ("Sustainability Finance", ["sustainable finance", "sustainability reporting", "esg analyst", "esg reporting", "climate finance", "carbon accounting"],
     ["sustainability reporting", "esg", "carbon accounting", "climate risk", "ifrs s1", "ifrs s2"], "sustainable finance"),
]

ADDITIONAL_QUERIES = [row[3] for row in SPECIALISMS] + [
    "finance intern", "graduate finance trainee", "chief financial officer",
    "insurance claims", "insurance sales", "banking relationship manager",
    "trade settlement", "valuation analyst", "private equity", "sap fico",
]

# Equivalent names only. Specific credentials and tool versions stay separate.
# CA Inter is not a qualified CA, and generic Excel is not Advanced Excel.
ALIASES = {
    "accounts receivable": ["accounts receivable", "account receivable", "receivables"],
    "order to cash": ["order to cash", "order-to-cash", "o2c", "otc"],
    "cash application": ["cash application", "cash applications"],
    "accounts payable": ["accounts payable", "account payable"],
    "procure to pay": ["procure to pay", "procure-to-pay", "p2p"],
    "record to report": ["record to report", "record-to-report", "r2r"],
    "fp&a": ["fp&a", "fp & a", "financial planning and analysis", "financial planning & analysis"],
    "financial modelling": ["financial modelling", "financial modeling"],
    "ar ageing": ["ar ageing", "ar aging"],
    "month end close": ["month end close", "month-end close"],
    "three way match": ["three way match", "three-way match", "3 way match"],
    "power bi": ["power bi", "powerbi"],
    "aml": ["aml", "anti money laundering", "anti-money laundering"],
    "kyc": ["kyc", "know your customer"],
    "discounted cash flow": ["discounted cash flow", "dcf"],
    "nav calculation": ["nav calculation", "net asset value calculation"],
    "value at risk": ["value at risk", "value-at-risk", "var"],
    "b.com": ["b.com", "bcom", "b com", "bachelor of commerce"],
    "m.com": ["m.com", "mcom", "m com", "master of commerce"],
    "cfa": ["cfa", "chartered financial analyst"],
    "frm": ["frm", "financial risk manager"],
    "ca": ["ca", "chartered accountant"],
    "ca inter": ["ca inter", "ca intermediate", "semi qualified ca", "semi-qualified ca"],
    "cma": ["cma", "cost and management accountant"],
    "cpa": ["cpa", "certified public accountant"],
    "nism": ["nism", "national institute of securities markets"],
}


@lru_cache(maxsize=None)
def _term_pattern(term):
    return re.compile(r"(?<![a-z0-9])" + re.escape(term) + r"(?![a-z0-9])")


def contains_term(text, term):
    return bool(_term_pattern(term).search(text.lower()))


def classify_finance(job):
    title = (job.get("title") or "").lower()
    body = " ".join(str(job.get(k) or "") for k in ("title", "skills", "description", "jd")).lower()
    best, strength = None, 0.0
    for name, title_terms, body_terms in JOB_FAMILIES:
        score = min(1.0, sum(contains_term(body, t) for t in body_terms) / 5)
        if any(contains_term(title, t) for t in title_terms):
            return name, "title", max(0.6, score)
        if score > strength:
            best, strength = name, score
    return best, "body" if best else None, strength


def listing_priority(job):
    """Public sorting aid, never a probability or a candidate assessment."""
    days = job.get("days_old")
    fresh = 0.35 if days is None else (1 if days <= 0 else 0.9 if days == 1 else 0.7 if days <= 3 else 0.45 if days <= 5 else 0.25 if days <= 7 else 0)
    applicants = job.get("applicants")
    competition = 0.4 if applicants is None else (1 if applicants <= 0 else 0.9 if applicants <= 10 else 0.75 if applicants <= 25 else 0.5 if applicants <= 50 else 0.28 if applicants <= 100 else 0.08)
    direct = {"direct": 1, "agency": 0.55}.get(job.get("posted_via"), 0.35)
    return round((direct * 26 + fresh * 22 + competition * 16) / 64 * 100)


def public_catalog():
    guides = {
        "Accounts Receivable": ["cash application", "collections", "dispute management", "ar ageing", "bank reconciliation", "order to cash"],
        "Credit & Collections": ["credit control", "collections", "dso", "dispute management", "credit limit"],
        "Accounting": ["bookkeeping", "journal entries", "bank reconciliation", "financial statements", "excel"],
    }
    return {"families": [
        {"name": name, "skills": guides.get(name, terms[:6])} for name, _, terms in JOB_FAMILIES
    ], "skills": SKILL_GROUPS}

BASE_FAMILIES = [('Accounts Receivable',
  ['accounts receivable',
   'receivable',
   'order to cash',
   'order-to-cash',
   'o2c',
   'invoice to cash',
   'cash application',
   'cash applications',
   'billing',
   'dunning',
   'ar analyst',
   'ar executive'],
  ['accounts receivable',
   'receivable',
   'receivables',
   'a/r',
   'ar ageing',
   'ar aging',
   'order to cash',
   'order-to-cash',
   'o2c',
   'invoice to cash',
   'i2c',
   'cash application',
   'cash applications',
   'cash allocation',
   'cash posting',
   'receipt posting',
   'collections',
   'collection',
   'dunning',
   'credit control',
   'credit management',
   'credit risk',
   'credit limit',
   'credit review',
   'credit hold',
   'dso',
   'days sales outstanding',
   'aging',
   'ageing',
   'past due',
   'overdue',
   'dispute',
   'dispute management',
   'deduction',
   'deductions',
   'chargeback',
   'short payment',
   'short-payment',
   'remittance',
   'remittance advice',
   'billing',
   'invoicing',
   'invoice',
   'e-invoicing',
   'customer master',
   'bad debt',
   'doubtful debt',
   'provision for doubtful',
   'write-off',
   'unapplied cash',
   'unallocated cash',
   'on-account',
   'customer statement',
   'lockbox',
   'sundry debtors',
   'debtors',
   'ar reconciliation']),
 ('Credit & Collections',
  ['collection',
   'collections',
   'credit control',
   'credit analyst',
   'credit risk',
   'credit manager',
   'recovery'],
  ['collections',
   'credit control',
   'credit limit',
   'credit review',
   'dso',
   'days sales outstanding',
   'past due',
   'overdue',
   'dunning',
   'credit risk',
   'bad debt',
   'recovery',
   'delinquency']),
 ('Accounts Payable',
  ['accounts payable',
   'procure to pay',
   'procure-to-pay',
   'p2p',
   'ap analyst',
   'ap executive',
   'invoice processing',
   'vendor payment',
   'accounts payable executive'],
  ['accounts payable',
   'vendor invoice',
   'vendor payment',
   'three way match',
   '3 way match',
   'purchase order',
   'po matching',
   'grn',
   'invoice booking',
   'vendor reconciliation',
   'payment run',
   'expense reimbursement',
   'travel and expense',
   't&e',
   'procure to pay']),
 ('Payroll',
  ['payroll', 'compensation and benefits', 'salary processing'],
  ['payroll',
   'salary processing',
   'pf',
   'esi',
   'gratuity',
   'form 16',
   'payroll reconciliation',
   'attendance',
   'full and final']),
 ('Tax',
  ['tax',
   'taxation',
   'gst',
   'transfer pricing',
   'indirect tax',
   'direct tax',
   'tax analyst',
   'tax manager'],
  ['gst',
   'tds',
   'income tax',
   'indirect tax',
   'direct tax',
   'transfer pricing',
   'tax return',
   'tax audit',
   'vat',
   'withholding',
   'statutory compliance',
   'tax provision',
   'deferred tax']),
 ('Audit & Compliance',
  ['audit',
   'internal audit',
   'statutory audit',
   'compliance',
   'sox',
   'risk and control',
   'internal control'],
  ['internal audit',
   'statutory audit',
   'sox',
   'internal controls',
   'audit report',
   'control testing',
   'risk assessment',
   'compliance',
   'walkthrough',
   'audit findings',
   'icfr']),
 ('Treasury',
  ['treasury', 'cash management', 'forex', 'fx ', 'liquidity'],
  ['treasury',
   'cash flow forecast',
   'liquidity',
   'forex',
   'hedging',
   'bank guarantee',
   'letter of credit',
   'investment',
   'borrowings',
   'cash management',
   'fund flow']),
 ('FP&A',
  ['fp&a',
   'financial planning',
   'budgeting',
   'business finance',
   'financial analyst',
   'planning and analysis',
   'cost accountant',
   'costing'],
  ['budgeting',
   'forecasting',
   'variance analysis',
   'financial modelling',
   'financial modeling',
   'mis',
   'management reporting',
   'cost analysis',
   'profitability',
   'ebitda',
   'business partnering',
   'scenario analysis']),
 ('General Ledger / R2R',
  ['general ledger',
   'record to report',
   'r2r',
   'gl accountant',
   'financial reporting',
   'month end',
   'reconciliation',
   'controller',
   'statutory reporting'],
  ['general ledger',
   'journal entries',
   'month-end close',
   'month end close',
   'record to report',
   'balance sheet reconciliation',
   'account reconciliation',
   'trial balance',
   'accruals',
   'prepaid',
   'fixed assets',
   'intercompany',
   'us gaap',
   'ifrs',
   'consolidation',
   'financial statements']),
 ('Accounting',
  ['accountant',
   'accounts',
   'accounting',
   'bookkeep',
   'finance executive',
   'finance associate',
   'finance officer',
   'accounts assistant',
   'finance manager',
   'finance'],
  ['bookkeeping',
   'tally',
   'vouchers',
   'ledger',
   'petty cash',
   'bank reconciliation',
   'invoice',
   'accounting',
   'book keeping',
   'day to day accounting',
   'quickbooks',
   'zoho books'])]

BASE_SKILLS = ['accounts receivable',
 'order to cash',
 'o2c',
 'invoice to cash',
 'cash application',
 'cash applications',
 'cash allocation',
 'cash posting',
 'collections',
 'credit control',
 'credit management',
 'credit risk',
 'dunning',
 'dso',
 'days sales outstanding',
 'ar ageing',
 'ar aging',
 'aging',
 'ageing',
 'dispute management',
 'disputes',
 'deductions',
 'chargebacks',
 'short payment',
 'remittance',
 'billing',
 'invoicing',
 'e-invoicing',
 'customer master',
 'bad debt',
 'provision for doubtful',
 'write-off',
 'unapplied cash',
 'lockbox',
 'debtors',
 'reconciliation',
 'bank reconciliation',
 'account reconciliation',
 'intercompany',
 'month-end close',
 'month end close',
 'revenue recognition',
 'unbilled revenue',
 'revenue assurance',
 'project billing',
 'milestone billing',
 'time and material',
 'pass-through',
 'sponsor reconciliation',
 'accounts payable',
 'general ledger',
 'journal entries',
 'gl reconciliation',
 'fixed assets',
 'variance analysis',
 'forecasting',
 'working capital',
 'cash flow',
 'audit',
 'internal controls',
 'sox',
 'us gaap',
 'ifrs',
 'statutory reporting',
 'sap',
 'sap fscm',
 'sap fi',
 's/4hana',
 'oracle',
 'oracle fusion',
 'oracle financials',
 'oracle r12',
 'peoplesoft',
 'netsuite',
 'microsoft dynamics',
 'dynamics 365',
 'tally',
 'quickbooks',
 'workday',
 'highradius',
 'blackline',
 'esker',
 'billtrust',
 'getpaid',
 'coupa',
 'concur',
 'alteryx',
 'advanced excel',
 'excel',
 'power bi',
 'power query',
 'vba',
 'macros',
 'sql',
 'tableau',
 'python',
 'erp',
 'automation',
 'rpa',
 'shared services',
 'gbs',
 'bpo',
 'stakeholder management',
 'process improvement',
 'six sigma',
 'lean',
 'kpi',
 'dashboard',
 'reporting',
 'ca',
 'cma',
 'cpa',
 'mba finance',
 'acca',
 'm.com',
 'b.com',
 'ca inter',
 'procure to pay',
 'p2p',
 'three way match',
 '3 way match',
 'purchase order',
 'po matching',
 'grn',
 'vendor reconciliation',
 'vendor master',
 'invoice booking',
 'payment run',
 'expense reimbursement',
 'travel and expense',
 't&e',
 'ap automation',
 'duplicate payment',
 'gst',
 'tds',
 'income tax',
 'indirect tax',
 'direct tax',
 'transfer pricing',
 'tax return',
 'tax audit',
 'tax provision',
 'deferred tax',
 'withholding tax',
 'vat',
 'gst returns',
 'gstr',
 'form 16',
 'e-way bill',
 'payroll',
 'payroll processing',
 'salary processing',
 'pf',
 'esi',
 'gratuity',
 'full and final',
 'payroll reconciliation',
 'compensation',
 'benefits administration',
 'attendance',
 'statutory compliance',
 'treasury',
 'cash management',
 'liquidity',
 'hedging',
 'forex',
 'fx',
 'letter of credit',
 'bank guarantee',
 'fund flow',
 'cash flow forecasting',
 'investments',
 'borrowings',
 'debt management',
 'fp&a',
 'budgeting',
 'financial planning',
 'financial modelling',
 'financial modeling',
 'mis',
 'mis reporting',
 'management reporting',
 'profitability analysis',
 'ebitda',
 'business partnering',
 'scenario analysis',
 'cost accounting',
 'costing',
 'standard costing',
 'inventory valuation',
 'margin analysis',
 'internal audit',
 'statutory audit',
 'risk assessment',
 'control testing',
 'icfr',
 'walkthrough',
 'trial balance',
 'accruals',
 'prepaid',
 'amortisation',
 'depreciation',
 'consolidation',
 'financial statements',
 'balance sheet',
 'p&l',
 'cash book',
 'petty cash',
 'vouchers',
 'ledger scrutiny',
 'zoho books',
 'xero',
 'busy']


JOB_FAMILIES = [(name, titles, skills) for name, titles, skills, _ in SPECIALISMS] + BASE_FAMILIES
# Keep whole words in the classifier; list inflections explicitly.
for _name, _titles, _skills in JOB_FAMILIES:
    if _name == "Accounting":
        _titles.extend(["bookkeeper", "bookkeeping", "finance intern", "finance trainee"])

_all_skills = list(dict.fromkeys(BASE_SKILLS + [term for _, _, skills in JOB_FAMILIES for term in skills] + list(ALIASES)))
_alias_names = {alias for aliases in ALIASES.values() for alias in aliases}
SKILL_GROUPS = [{"name": name, "aliases": aliases} for name, aliases in ALIASES.items()]
SKILL_GROUPS += [{"name": name, "aliases": [name]} for name in _all_skills if name not in _alias_names]
SKILL_VOCAB = list(dict.fromkeys(alias for group in SKILL_GROUPS for alias in group["aliases"]))
